### ISSUE TITLE
Runtime zip files not unzipping

### ISSUE THREAD

**Issue by mikewl** [vsClojure/vsClojure#136] opened 2013-12-30 21:16 UTC
When installing the vsClojure extension, the zip files in the runtimes folder do not unzip.
Microsoft.VisualStudio.Package.LanguageService.10.0.dll is present in the Extensions/[Random Letters/ folder.

Visual studio 2013 and sql server express 2014 ctp2 are installed on window 8.1 x64.

**Comment by frankhale** [comment] 2013-12-30 22:02
Hi Mike,

Do you see this behavior with the latest version from the Visual Studio gallery? Or from the code here on Github?

**Comment by mikewl** [comment] 2013-12-30 22:03
The latest version from the Visual Studio Gallery, I built it myself with the same issue however. Will rebuild and check again.

**Comment by frankhale** [comment] 2013-12-30 22:04
Okay, Thank you!

**Comment by mikewl** [comment] 2013-12-30 22:08
I built it and checked. Both the ones stored in 12.0Exp and 12.0 don't unzip, the languageservice dll is present however.

**Comment by frankhale** [comment] 2013-12-31 02:46
What is in the following folder on your system? Is it completely empty?

```
C:\Users\<your_user_name>\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\<random_dir_name>\Runtimes
```

**Comment by mikewl** [comment] 2013-12-31 10:06
ClojureCLR-1.5.0.zip
ClojureScript-1.5.0.zip

These are in the Runtimes folder

**Comment by frankhale** [comment] 2013-12-31 13:45
Okay, just confirming. Those two zips should not even exist there. They
should definitely be unzipped. Why was this closed?

**Comment by mikewl** [comment] 2013-12-31 14:22
I seem to have confused closing the editbox with closing the issue sorry!

**Comment by frankhale** [comment] 2014-01-08 16:12
Is .NET 3.5 installed on your machine?

**Comment by frankhale** [comment] 2014-01-08 16:18
Did not mean to close this. Fat fingers! ARGH!

**Comment by mikewl** [comment] 2014-01-08 17:16
Glad to see I am not the only one who mis clicks! It is not installed, it is busy installing (and has been for awhile now thanks to the slow internet.) Will update as soon as it is installed.
EDIT: All of the projects target .NET 4, so not sure of how much of an effect this will have.

**Comment by mikewl** [comment] 2014-01-08 17:44
Strange, it works!
It now leaves an error on start however,
"ShowClojureProjectMenuCommands: Value cannot be null. Parameter name: path1"

Any idea on what is going on there?

The Clojure.dll reference does not work however, is this intended?

**Comment by frankhale** [comment] 2014-01-08 17:46
Sorry, that was a debug statement that I inserted in a try/catch block.
Ignore it. I thought I removed that. I'll go back and check.

**Comment by mikewl** [comment] 2014-01-08 17:53
I can't compile anything now. Though I can successfully create a project now. It also does the intended restart. The Clojure.dll reference doesn't function. It can't find the .dll

**Comment by mikewl** [comment] 2014-01-08 18:09
![Uploading issue.PNG . . .]()
This is the new error on startup now.

**Comment by frankhale** [comment] 2014-01-08 18:11
I can't see the screenshot.

**Comment by mikewl** [comment] 2014-01-08 18:12
![issue](https://f.cloud.github.com/assets/3878949/1870999/4cf70a50-7890-11e3-8f34-4cc4a5756a0b.PNG)
Excuse my internet being silly

**Comment by speige** [comment] 2014-02-05 00:54
The exception you caused makes sense as to why the runtime wasn't unzipped. 

The method ShowClojureProjectMenuCommands() is called before UnzipRuntimes() in ClojurePackage.cs

Because the null value is in Path.Combine of that method, I think the issue is the Utilities.EnvironmentVariables.VsClojureRuntimesDir. This environment variable isn't set until later in the EnableSettingOfRuntimePathForNewClojureProjects() method.

The strange thing is, this should be failing for everyone. I've brand virtual machines with clean installs and haven't seen this. I wonder if it's an issue with the current GitHub commit & not with the uploaded visual studio extension? I'll investigate this a bit more tonight.

Fyi, the normal installation process (which i see on my clean VM when using the gallery version) show be like this:
Visual Studio makes you restart 2X after installing vsClojure. The 1st is from inside the the tools/extensions window after vsClojure downloads & installs. At this point, you should see .zip files in your runtimes folder. When you click restart, visual studio should auto-restart. When visual studio finishes loading after the restart, the .zip files should have been unzipped. You'll know it's done because you'll see a popup message box which asks you to restart & asks if you want to see the readme. This time, you'll have to manually restart. 

I'll rearrange the environment variable code & we'll see if that makes a difference for you.

Sorry about the long wait on this issue, I'll try to be more prompt in the future.

**Comment by frankhale** [comment] 2014-02-05 01:01
I'm pretty sure he also tried the one from the gallery and reported the same issue.

**Comment by speige** [comment] 2014-02-05 15:14
I committed a change that might fix this unzipping issue. Do you want to pull the latest from GitHub, compile, and try it out? Alternatively, I can put the .vsix online somewhere.

**Closed as completed** 2014-02-22 11:31 UTC
Labels: Need More Information
