### ISSUE TITLE
Allow period in .clj file to compile with MSBuild Clojure.Compile.exe task

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#97] opened 2013-12-11 07:46 UTC
If you name a clojure file my.namespace.clj, it confuses the MSBuild compile task.

**Comment by frankhale** [comment] 2013-12-11 14:00
Does it also confuse the Clojure compiler? I think I was having some issues
compiling some code that had a period in the file name like you mentioned.
I could be mistaken, I know I definitely had issues with - and underscores
but that was likely my confusion rather than the compilers.

**Comment by speige** [comment] 2013-12-13 05:30
You're right, this is a Clojure.Compile.exe issue, not an MSBuild issue. My mistake.

**Comment by frankhale** [comment] 2013-12-13 19:35
This should probably be closed then because this issue is not really a bug but behavior as designed and enforced by the Clojure compiler?

**Comment by speige** [comment] 2013-12-13 19:44
I agree, but we should probably move the issue to https://github.com/clojure/clojure-clr

**Comment by speige** [comment] 2013-12-13 19:45
I guess it should technically be at http://dev.clojure.org/jira as well, under the ClojureCLR section.

**Comment by frankhale** [comment] 2013-12-13 19:59
Do you know off the top of your head if the Clojure JVM compiler allows for periods in the name of files?

**Comment by frankhale** [comment] 2013-12-18 01:53
I had an issue with dashes and posted a question to the Clojure mailing list. David replied and said that ClojureCLR follows the same file naming convention as the JVM version. I'm going to close this issue. I think we should probably discourage people from using periods in their file name unless it's for the clj extension.

**Closed as completed by frankhale** 2013-12-18 01:53 UTC
Labels: Bug

**Comment by speige** [comment] 2013-12-18 02:17
Can we research why the .clj file has to match the name given to gen-class?

**Comment by frankhale** [comment] 2013-12-18 02:46
Sure!

**Comment by frankhale** [comment] 2013-12-18 02:54
Without even looking into this I think the reason for the naming convention is that in Java land the name of the file corresponds to the name of the top level public class. ClojureCLR follows the same naming conventions as the JVM implementation.

This is worth looking at but it doesn't directly support what I just said: https://kotka.de/blog/2010/02/gen-class_how_it_works_and_how_to_use_it.html
